ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: ${PORT:8080}
jwt:
  domain: ${JWT_DOMAIN}
  audience: ${JWT_AUDIENCE}
  realm: ${JWT_REALM}
  secret: ${JWT_SECRET}
db:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

#jwt:
#  domain: "https://jwt-provider-domain/"
#  audience: "jwt-audience"
#  realm: "ktor sample app"
#  secret: "secret"
#db:
#  url: "r2dbc:postgresql://localhost:5432/zorvyn_assignment"
#  user: "postgres"
#  password: ""
